# Function in Array

In [1]:
import numpy as np

In [2]:
n=np.array([2,98,3,6,5,4,3])
n

array([ 2, 98,  3,  6,  5,  4,  3])

In [4]:
#sorting
n.sort()
n

array([ 2,  3,  3,  4,  5,  6, 98])

In [5]:
h=np.array([3,4,5,6,3,3,2])
np.concatenate([n,h])

array([ 2,  3,  3,  4,  5,  6, 98,  3,  4,  5,  6,  3,  3,  2])

# Function in 2d Array

In [11]:
a=np.array([[2,3],[2,3]])
b=np.array([[2,3],[3,62]])
f=np.concatenate((a,b),axis=0)
f


array([[ 2,  3],
       [ 2,  3],
       [ 2,  3],
       [ 3, 62]])

In [12]:
# to find the dinamasion
f.ndim

2

In [13]:
# to find the size 
f.size

8

In [14]:
# to find the shape
f.shape

(4, 2)

In [16]:
# Reshape the array
g=np.arange(9)
g
g.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])